#include <arpa/inet.h>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <sys/socket.h>
#include <unistd.h>
static constexpr int P=160,K=4,N=6,S=2048;
static unsigned char m(unsigned char a,unsigned char b){unsigned char r=0;while(b){if(b&1)r^=a;a=(a&128)?(unsigned char)((a<<1)^29):(unsigned char)(a<<1);b>>=1;}return r;}static unsigned char pw(unsigned char a,int n){unsigned char r=1;while(n){if(n&1)r=m(r,a);a=m(a,a);n>>=1;}return r;}static unsigned char iv(unsigned char a){return pw(a,254);}static unsigned char c(int r,int col){if(r<K)return r==col;unsigned char v=1,b=1u<<(r-K);for(int i=0;i<col;i++)v=m(v,b);return v;}
struct G{uint32_t base=UINT32_MAX;unsigned char got[N]{},sent[K]{},d[N][P]{};};
static bool invert(unsigned char a[K][K],unsigned char out[K][K]){unsigned char z[K][2*K]{};for(int i=0;i<K;i++)for(int j=0;j<K;j++){z[i][j]=a[i][j];z[i][K+j]=(i==j);}for(int col=0;col<K;col++){int q=col;while(q<K&&!z[q][col])q++;if(q==K)return false;if(q!=col)for(int j=0;j<2*K;j++){unsigned char t=z[col][j];z[col][j]=z[q][j];z[q][j]=t;}unsigned char scale=iv(z[col][col]);for(int j=0;j<2*K;j++)z[col][j]=m(z[col][j],scale);for(int r=0;r<K;r++)if(r!=col&&z[r][col]){unsigned char f=z[r][col];for(int j=0;j<2*K;j++)z[r][j]^=m(f,z[col][j]);}}for(int i=0;i<K;i++)for(int j=0;j<K;j++)out[i][j]=z[i][K+j];return true;}
int main(){int in=socket(AF_INET,SOCK_DGRAM,0),out=socket(AF_INET,SOCK_DGRAM,0);sockaddr_in a{};a.sin_family=AF_INET;a.sin_port=htons(47002);a.sin_addr.s_addr=htonl(INADDR_LOOPBACK);if(bind(in,(sockaddr*)&a,sizeof a)<0){perror("bind 47002");return 1;}sockaddr_in player{};player.sin_family=AF_INET;player.sin_port=htons(47020);player.sin_addr.s_addr=htonl(INADDR_LOOPBACK);G gs[S];unsigned char p[165];auto emit=[&](uint32_t seq,const unsigned char*x){unsigned char f[164];uint32_t n=htonl(seq);memcpy(f,&n,4);memcpy(f+4,x,P);sendto(out,f,sizeof f,0,(sockaddr*)&player,sizeof player);};for(;;){if(recvfrom(in,p,sizeof p,0,nullptr,nullptr)!=165||p[0]>=N)continue;uint32_t nb;memcpy(&nb,p+1,4);uint32_t base=ntohl(nb);G&g=gs[(base/K)%S];if(g.base!=base){g=G{};g.base=base;}int row=p[0];if(g.got[row])continue;g.got[row]=1;memcpy(g.d[row],p+5,P);if(row<K&&!g.sent[row]){emit(base+row,g.d[row]);g.sent[row]=1;}int n=0,rows[K];for(int r=0;r<N;r++)if(g.got[r]&&n<K)rows[n++]=r;if(n<K)continue;unsigned char a[K][K],v[K][K],ans[K][P]{};for(int r=0;r<K;r++)for(int col=0;col<K;col++)a[r][col]=c(rows[r],col);if(!invert(a,v))continue;for(int col=0;col<K;col++)for(int b=0;b<P;b++)for(int r=0;r<K;r++)ans[col][b]^=m(v[col][r],g.d[rows[r]][b]);for(int col=0;col<K;col++)if(!g.sent[col]){emit(base+col,ans[col]);g.sent[col]=1;}}}
